apiVersion: apps/v1
kind: Deployment
metadata:
  name: pw-leak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pw-leak
  template:
    metadata:
      labels:
        app: pw-leak
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: credentials
          items:
          - key: password
            path: index.html

      containers:
      - name: leaker
        image: nginx
        volumeMounts:
        - name: secret-volume
          mountPath: /usr/share/nginx/html
          readOnly: true

---
# ignore this, we'll explain services soon!
# kubectl port-forward service/pw-leak 8080:80 &
# curl localhost:8080
apiVersion: v1
kind: Service
metadata:
  name: pw-leak
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pw-leak
