apiVersion: apps/v1
kind: Deployment
metadata:
  name: param-secret-app
  labels:
    demo: param-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: param-secret-app
  template:
    metadata:
      labels:
        app: param-secret-app
        demo: param-secret-app
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: credentials
      containers:
        - name: param-secret-app
          # kubectl logs -f deployments/param-secret-app -c color-env
          image: ghcr.io/chtime/via:master
          ports:
            - containerPort: 8000
          env:
            - name: VOLUMES_PATH
              value: /volumes
          # if there are many more entries in a config map, pull them all:
          envFrom:
            - secretRef:
                name: credentials
          volumeMounts:
            - name: secret-volume
              mountPath: /volumes/secrets
