apiVersion: apps/v1
kind: Deployment
metadata:
  name: param-cm-app
  labels:
    demo: param-cm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: param-cm-app
  template:
    metadata:
      labels:
        app: param-cm-app
        demo: param-cm-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      containers:
        - name: param-cm-app
          # kubectl logs -f deployments/param-cm-app -c color-env
          image: ghcr.io/chtime/via:master
          ports:
            - containerPort: 8000
          env:
            - name: STAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: stage
            - name: VOLUMES_PATH
              value: /volumes
          # if there are many more entries in a config map, pull them all:
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: config-volume
              mountPath: /volumes/config
