apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxpod
  name: nginxpod 
spec:
  containers:
  - image: nginx 
    #command: ["/bin/sh"]
    #args: ["-c", "echo Hello World > /opt/time.out"]
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data-volume   
    name: timepod
    resources: {}
  volumes:
  - name: data-volume
    hostPath:
      path: /run/desktop/mnt/host/c/Temp
      type: DirectoryOrCreate  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
