apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
    - image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data-volume
      name: nginxpod
      resources: {}
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pv-hostpath-claim
