apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginxpod
  name: nginxpod
spec:
  containers:
    - image: nginx
      name: nginxpod
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /run/desktop/mnt/host/c/Temp
        type: DirectoryOrCreate
