# --------------------------
# secretProviderClass.yaml
# --------------------------
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-secrets
spec:
  provider: platform # this provider abstracts away HashiCorp Vault and Thycotic

  # --------------------------------------------------------------------------------------------------
  # mandatory section referencing the hashicorp vault secret(s) that will be mounted as a volume
  # --------------------------------------------------------------------------------------------------
  # objectName: corresponds to the mounted file name
  # secretPath: path to the secret in vault ("data" must be added in second position)
  # secretKey; key (name) of the secret in vault
  parameters:
    objects: |
      - objectName: "test-secret"
        secretPath: "kv/data/test"
        secretKey: "test"

  # --------------------------------------------------------------------------------------------------
  # Optional declaration of a Kubernetes secret that will mirror the mounted secret upon pod startup
  # --------------------------------------------------------------------------------------------------
  secretObjects:
    - secretName: db-password # name of the Kubernetes secret you want to create
      type: Opaque # type of the Kubernetes secret
      data: # data section of the Kubernetes secret
        - objectName: kv # must match the objectName from the parameters section
          key: test # key (name) of the secret within the data section (the value will be the actual secret you want to use)
