apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app
  demo: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: some-app
  template:
    metadata:
      labels:
        app: some-app
    spec:
      containers:
        - name: some-app
          image: ghcr.io/chtime/via:master
          ports:
            - containerPort: 8000
