apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-quota
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-quota
  template:
    metadata:
      labels:
        app: webserver-quota
    spec:
      containers:
        - name: webserver-quota
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

