apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
  labels:
    demo: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
        demo: probes
    spec:
      containers:
        - name: readiness
          image: ghcr.io/chtime/via:master
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /no-coffee
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
