apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness
  labels:
    demo: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
        demo: probes
    spec:
      containers:
        - name: liveness
          image: ghcr.io/chtime/via:master
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: "/💀"
            failureThreshold: 10
            successThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
