apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup
  labels:
    demo: probes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startup
  template:
    metadata:
      labels:
        app: startup
        demo: probes
    spec:
      containers:
        - name: startup
          image: ghcr.io/chtime/via:master
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "sleeping...";
              sleep 30;
              echo "starting";
              exec ./serve.sh
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet:
              port: 8000
              path: /
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
