apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-rp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-rp
  template:
    metadata:
      labels:
        app: webserver-rp
    spec:
      containers:
        - name: webserver-rp
          image: nginx:1-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              port: 8080
              path: /no-coffee
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
