apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-lp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-lp
  template:
    metadata:
      labels:
        app: webserver-lp
    spec:
      containers:
        - name: webserver-lp
          image: nginx:1-alpine
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 8080
              path: "/💀"
            failureThreshold: 10
            successThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 1
            timeoutSeconds: 1
