apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx-sts # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-sts # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "hostpath" # Specific StorageClass for Docker Desktop
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-sts
  labels:
    app: nginx-sts
spec:
  ports:
    - port: 80
      name: web
      targetPort: web
      nodePort: 30888
  type: NodePort
  sessionAffinity: None
  selector:
    app: nginx-sts
