apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-app
  labels:
    demo: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-app
  template:
    metadata:
      labels:
        app: storage-app
        demo: storage
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: storage-app-pvc
      containers:
        - name: storage-app
          image: ghcr.io/chtime/via:master
          ports:
            - containerPort: 8000
          env:
            - name: VOLUMES_PATH
              value: /volumes
          volumeMounts:
            - name: data-volume
              mountPath: /volumes/data
