apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage-app
    demo: storage
  name: storage-app
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: storage-app
  type: ClusterIP
