apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  # for better portability, leave the storage class used as default.
  # storageClassName: hostpath
