apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-hostpath-claim 
spec:
  storageClassName:  local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi    
