apiVersion: v1
kind: Pod
metadata:
  name: vote-app
spec:
  containers:
  - image: eesprit/voting-app-vote
    imagePullPolicy: IfNotPresent
    name: vote-app
    ports:
    - containerPort: 80
      protocol: TCP
