apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: gcr.io/google-samples/hello-app
  newTag: '2.0'


namePrefix: development-
commonAnnotations:
  note: Hello, I am dev!

resources:
- ../../base
