apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes-config
  template:
    metadata:
      labels:
        app: hello-kubernetes-config
    spec:
      containers:
        - name: hello-kubernetes-config
          image: "paulbouwer/hello-kubernetes:1.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTAINER_IMAGE
            value: "paulbouwer/hello-kubernetes:1.10"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: hello-kubernetes-config
                key: message

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-kubernetes-config
  labels:
    app: hello-kubernetes-config
data:
  message: "🔥 inside a ConfigMap"

---

apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-config
  labels:
      app: hello-kubernetes-config
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      nodePort: 31323
      protocol: TCP
      name: http
  selector:
    app: hello-kubernetes-config