apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secrets-app
  template:
    metadata:
      labels:
        app: secrets-app
    spec:
      containers:
        - name: secrets-app
          image: ghcr.io/chtime/via:master
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: MESSAGE
              valueFrom:
                secretKeyRef:
                  name: secrets-app
                  key: message

---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-app
  labels:
    app: secrets-app
stringData:
  message: "🥷 is hiding in a secret"

---
apiVersion: v1
kind: Service
metadata:
  name: secrets-app
  labels:
    app: secrets-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: secrets-app
