apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: config-app
      containers:
        - name: config-app
          image: ghcr.io/chtime/via:master
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: config-app
                  key: message
            - name: VOLUMES_PATH
              value: /volumes
          envFrom:
            - configMapRef:
                name: config-app
          volumeMounts:
            - name: config-volume
              mountPath: /volumes/config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app
  labels:
    app: config-app
data:
  message: "🔥 inside a ConfigMap"
  unused: "config"

---
apiVersion: v1
kind: Service
metadata:
  name: config-app
  labels:
    app: config-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: config-app
